GET https://95abde56-028d-4c19-9cae-fd4c00cf54d9-00-1lji1cvl1zomi.riker.replit.dev/contato HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW4iLCJwcm9maWxlIjoiYWRtaW4iLCJpYXQiOjE3MTM3OTY1MDUsImV4cCI6MTcxMzc5NjgwNX0.ZSHSFEeTdGlnz2oLhXhhBj-6c1DougadhGHG0ZtWToQ